# Copyright (c) 2023, MASSACHUSETTS INSTITUTE OF TECHNOLOGY
# Subject to FAR 52.227-11 - Patent Rights - Ownership by the Contractor (May 2014).
#
# Training config for the CuxO bulk charge-density model.
defaults:
  - model: e3_density
  - data: mp_data
  - _self_

# number of nodes
nnodes: 1
# number of processes/devices per node
nprocs: 1

# training steps
steps: 1e6

# (optional) save cubes on test
cube_dir:

# checkpoint, will resume training if path exists
checkpoint_path:

# tensorboard, logs, and tmp files
log_dir: ${hydra:run.dir}

seed: 42
cutoff: 4.0
batch_size: 32
split: "split_v2"
lr: 0.005

hydra:
  job:
    name: cuxo_bulk
  run:
    dir: ./results/charge3net/${hydra.job.name}/${now:%Y-%m-%d}
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback

data:
  batch_size: ${batch_size}
  train_workers: 8
  val_workers: 8
  pin_memory: False
  train_probes: 100
  val_probes: 400
  test_probes: 1000
  split_file: ./data/mp/${split}.json
  graph_constructor:
    cutoff: ${cutoff}
    disable_pbc: False

model:
  optimizer:
    lr: ${lr}
  lr_scheduler:
    beta: 3e3
  model:
    cutoff: ${cutoff}
